# Generated by Django 4.2.4 on 2025-03-10 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Día festivo o excepción')),
                ('is_off', models.BooleanField(default=True, help_text='Si está libre este día entero')),
                ('nurse', models.ForeignKey(limit_choices_to={'user_type': 'nurse'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
