# Generated by Django 4.2.4 on 2025-02-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='identification_number',
        ),
        migrations.AddField(
            model_name='user',
            name='identification_number',
            field=models.CharField(blank=True, help_text='Cédula o identificación personal', max_length=20, null=True, unique=True),
        ),
    ]
