# Generated by Django 4.2.4 on 2025-03-10 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('users', '0003_holidayexception'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurseprofile',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Localidad asignada para trabajo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nurses', to='common.location'),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Localidad asignada para trabajo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sellers', to='common.location'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
