# Generated by Django 6.0 on 2026-03-14 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#3366cc', help_text='Color para el badge en el dashboard', max_length=20)),
            ],
            options={
                'verbose_name': 'Etiqueta CRM',
                'verbose_name_plural': 'Etiquetas CRM',
            },
        ),
        migrations.CreateModel(
            name='Farmacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código de Farmacia')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de Farmacia')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='farmacias', to='main.ciudad')),
            ],
            options={
                'verbose_name': 'Farmacia',
                'verbose_name_plural': 'Farmacias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CrmContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=150, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('cedula', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cédula/RUC')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono (WhatsApp)')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('zona_barrio', models.CharField(blank=True, max_length=200, null=True, verbose_name='Zona / Barrio')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contactos_crm', to='main.ciudad')),
                ('usuario_vinculado', models.OneToOneField(blank=True, help_text='Usuario real del ERP/App si fue convertido.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_crm', to=settings.AUTH_USER_MODEL)),
                ('etiquetas', models.ManyToManyField(blank=True, related_name='contactos', to='crm_marketing.etiqueta')),
                ('farmacia_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactos', to='crm_marketing.farmacia')),
            ],
            options={
                'verbose_name': 'Contacto CRM',
                'verbose_name_plural': 'Contactos CRM',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='CampanaDifusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Campaña')),
                ('mensaje_plantilla', models.TextField(verbose_name='Mensaje de WhatsApp')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PROGRAMADA', 'Programada'), ('ENVIANDO', 'Enviando...'), ('COMPLETADA', 'Completada'), ('ERROR', 'Error')], default='BORRADOR', max_length=20)),
                ('fecha_programada', models.DateTimeField(blank=True, null=True, verbose_name='Enviar a partir de')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ciudades_objetivo', models.ManyToManyField(blank=True, to='main.ciudad', verbose_name='Filtro por Ciudad')),
                ('etiquetas_objetivo', models.ManyToManyField(blank=True, to='crm_marketing.etiqueta', verbose_name='Filtro por Etiquetas')),
                ('farmacias_objetivo', models.ManyToManyField(blank=True, to='crm_marketing.farmacia', verbose_name='Filtro por Farmacias')),
            ],
            options={
                'verbose_name': 'Campaña de Difusión',
                'verbose_name_plural': 'Campañas de Difusión',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
