# Generated by Django 6.0 on 2026-03-15 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoCRM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre Comercial')),
            ],
            options={
                'verbose_name': 'Producto (Lead Farmacia)',
                'verbose_name_plural': 'Productos (Leads Farmacias)',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='campanadifusion',
            name='edad_maxima',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad Máxima (Filtro)'),
        ),
        migrations.AddField(
            model_name='campanadifusion',
            name='edad_minima',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad Mínima (Filtro)'),
        ),
        migrations.AddField(
            model_name='crmcontact',
            name='es_edad_estimada',
            field=models.BooleanField(default=False, help_text='True si no se dio fecha exacta y se calculó el año base a su edad proporcionada.'),
        ),
        migrations.AddField(
            model_name='campanadifusion',
            name='medicamentos_objetivo',
            field=models.ManyToManyField(blank=True, to='crm_marketing.productocrm', verbose_name='Filtro por Productos/Medicamentos'),
        ),
        migrations.AddField(
            model_name='crmcontact',
            name='medicamentos_comprados',
            field=models.ManyToManyField(blank=True, related_name='compradores', to='crm_marketing.productocrm'),
        ),
        migrations.CreateModel(
            name='DiffusionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enviado_con_exito', models.BooleanField(default=False)),
                ('mensaje_error', models.TextField(blank=True, null=True)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='crm_marketing.campanadifusion')),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_difusion', to='crm_marketing.crmcontact')),
            ],
            options={
                'verbose_name': 'Log de Difusión',
                'verbose_name_plural': 'Logs de Difusión',
                'ordering': ['-fecha_envio'],
                'unique_together': {('campana', 'contacto')},
            },
        ),
    ]
