# Generated by Django 6.0 on 2026-03-17 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_marketing', '0002_productocrm_campanadifusion_edad_maxima_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeCampana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Envío'), ('ENVIADO', 'Enviado (API)'), ('LEIDO', 'Leído (Doble Check)'), ('ERROR', 'Error de Envío')], default='PENDIENTE', max_length=20)),
                ('wasender_message_id', models.CharField(blank=True, max_length=150, null=True, verbose_name='ID de Mensaje en WASender')),
                ('error_log', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_cola', to='crm_marketing.campanadifusion')),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_campana', to='crm_marketing.crmcontact')),
            ],
            options={
                'verbose_name': 'Mensaje de Campaña',
                'verbose_name_plural': 'Mensajes de Campaña',
                'unique_together': {('campana', 'contacto')},
            },
        ),
    ]
