# Generated by Django 6.0 on 2026-03-18 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_marketing', '0003_mensajecampana'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmcontact',
            name='etapa_comercial',
            field=models.CharField(choices=[('LEAD', 'Lead Entrante'), ('CONTACTADO', 'Primer Contacto'), ('NEGOCIACION', 'En Negociación'), ('GANADO', 'Venta Cerrada (Éxito)'), ('PERDIDO', 'Venta Perdida')], default='LEAD', max_length=20, verbose_name='Etapa del Pipeline'),
        ),
    ]
