# Generated by Django 6.0 on 2026-03-23 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_marketing', '0004_crmcontact_etapa_comercial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmcontact',
            name='es_organico',
            field=models.BooleanField(default=False, verbose_name='¿Es Orgánico? (WhatsApp)'),
        ),
    ]
