# Generated by Django 6.0 on 2026-03-23 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_marketing', '0005_crmcontact_es_organico'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmcontact',
            name='whatsapp_jid',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='WhatsApp JID / LID'),
        ),
    ]
