# Generated by Django 6.0 on 2026-03-24 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_marketing', '0006_crmcontact_whatsapp_jid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmcontact',
            name='telefono',
            field=models.CharField(max_length=20, unique=True, verbose_name='Teléfono (WhatsApp)'),
        ),
    ]
