# Generated by Django 6.0 on 2026-03-24 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_marketing', '0008_alter_crmcontact_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmcontact',
            name='cedula',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Cédula/RUC'),
        ),
    ]
