# Generated by Django 6.0 on 2026-03-24 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_marketing', '0009_alter_crmcontact_cedula'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrmConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_alerta_leads', models.PositiveIntegerField(default=30, help_text='Tiempo en minutos para resaltar leads sin atender')),
                ('respuestas_rapidas', models.JSONField(default=list, help_text="Lista de objetos { 'label': '...', 'text': '...' }")),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración CRM',
                'verbose_name_plural': 'Configuraciones CRM',
            },
        ),
        migrations.AddField(
            model_name='crmcontact',
            name='fecha_creacion_lead',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Creación del Lead'),
        ),
        migrations.AddField(
            model_name='crmcontact',
            name='fecha_primer_contacto',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Primer Contacto'),
        ),
        migrations.AddField(
            model_name='crmcontact',
            name='tiempo_respuesta_inicial',
            field=models.DurationField(blank=True, null=True, verbose_name='Tiempo de Respuesta Inicial'),
        ),
    ]
