# Generated by Django 6.0 on 2026-03-24 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_marketing', '0010_crmconfig_crmcontact_fecha_creacion_lead_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrmMediaTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Plantilla (Ej: Cuenta Banco)')),
                ('archivo', models.FileField(upload_to='crm/templates/', verbose_name='Archivo Multimedia')),
                ('tipo', models.CharField(choices=[('IMAGE', 'Imagen'), ('VIDEO', 'Video'), ('DOCUMENT', 'Documento/PDF')], default='IMAGE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plantilla Multimedia',
                'verbose_name_plural': 'Plantillas Multimedia',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
