# Generated by Django 6.0 on 2026-03-25 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_marketing', '0011_crmmediatemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmcontact',
            name='whatsapp_lid',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='WhatsApp LID (Linked Device ID)'),
        ),
        migrations.AlterField(
            model_name='crmcontact',
            name='whatsapp_jid',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='WhatsApp JID'),
        ),
    ]
