# Generated by Django 6.0 on 2026-03-25 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_marketing', '0012_crmcontact_whatsapp_lid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmcontact',
            name='es_proveedor',
            field=models.BooleanField(default=False, verbose_name='Es Proveedor (Oculto de Pipeline)'),
        ),
    ]
