# Generated by Django 6.0 on 2026-03-25 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_marketing', '0013_crmcontact_es_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajecampana',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Envío'), ('ENVIADO', 'Enviado (API)'), ('ENTREGADO', 'Entregado (Check Gris)'), ('LEIDO', 'Leído (Check Azul)'), ('ERROR', 'Error de Envío')], default='PENDIENTE', max_length=20),
        ),
    ]
