# Generated by Django 6.0 on 2026-04-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_marketing', '0014_alter_mensajecampana_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmcontact',
            name='fecha_ultima_actividad',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha última actividad'),
        ),
        migrations.AlterField(
            model_name='crmcontact',
            name='etapa_comercial',
            field=models.CharField(choices=[('LEAD', 'Lead Entrante'), ('CONTACTADO', 'Primer Contacto'), ('NEGOCIACION', 'En Negociación'), ('GANADO', 'Venta Cerrada (Éxito)'), ('PERDIDO', 'Venta Perdida'), ('DESCARTADO', 'Descartado / Competencia')], default='LEAD', max_length=20, verbose_name='Etapa del Pipeline'),
        ),
    ]
