# Generated by Django 4.2.4 on 2025-11-20 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0002_appointmentreminder_alter_appointmentstatus_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones_tecnicas', models.TextField(blank=True, verbose_name='Observaciones del Procedimiento')),
                ('foto_evidencia', models.ImageField(blank=True, null=True, upload_to='reportes/evidencias/')),
                ('firma_paciente_digital', models.ImageField(blank=True, help_text='Imagen de la firma digital capturada en pantalla', null=True, upload_to='reportes/firmas/')),
                ('requiere_seguimiento', models.BooleanField(default=False, help_text='Si marcas esto, se creará una alerta para agendar la próxima visita.', verbose_name='¿Requiere Siguiente Dosis?')),
                ('fecha_sugerida_seguimiento', models.DateField(blank=True, null=True, verbose_name='Fecha Próxima Dosis')),
                ('notas_seguimiento', models.TextField(blank=True, help_text='Ej: Neurobión cada 24h por 3 días.', verbose_name='Detalle Receta/Tratamiento')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reporte_servicio', to='appointments.appointment', verbose_name='Cita Vinculada')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte de Servicio',
                'verbose_name_plural': 'Reportes de Servicios',
            },
        ),
    ]
