# Generated by Django 4.2.4 on 2025-11-24 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=5, verbose_name='Calificación (1-5)')),
                ('comentario', models.TextField(blank=True, verbose_name='Comentario del Cliente')),
                ('origen', models.CharField(choices=[('WEB_HUERFANO', 'Formulario Web (Lead)'), ('APP_CLIENTE', 'App/Portal Cliente')], default='WEB_HUERFANO', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('enfermero', models.ForeignKey(help_text='Enfermero al que el cliente está calificando.', limit_choices_to={'rol': 'ENFERMERO'}, on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_recibidas', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(limit_choices_to={'rol': 'CLIENTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_dadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calificación de Servicio',
                'verbose_name_plural': 'Calificaciones (Feedback)',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
