# Generated by Django 4.2.4 on 2025-11-20 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Estado de Cita',
                'verbose_name_plural': 'Estados de Cita',
            },
        ),
        migrations.CreateModel(
            name='NurseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_especifica', models.DateField(blank=True, null=True)),
                ('dia_semana', models.IntegerField(blank=True, choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], null=True)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('descanso_inicio', models.TimeField(blank=True, null=True)),
                ('descanso_fin', models.TimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('enfermero', models.ForeignKey(limit_choices_to={'rol': 'ENFERMERO'}, on_delete=django.db.models.deletion.CASCADE, related_name='turnos_trabajo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Disponibilidad Enfermero',
                'verbose_name_plural': 'Disponibilidad Enfermeros',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField(verbose_name='Hora Inicio Cita')),
                ('hora_fin', models.TimeField(blank=True, editable=False, null=True, verbose_name='Hora Fin')),
                ('tipo_ubicacion', models.CharField(choices=[('DOMICILIO', 'A Domicilio'), ('LOCAL', 'En Local / Base'), ('OTRA', 'Otra Ubicación')], default='DOMICILIO', max_length=20)),
                ('direccion_servicio', models.TextField(blank=True, verbose_name='Dirección Escrita')),
                ('referencia_servicio', models.TextField(blank=True, null=True, verbose_name='Referencia')),
                ('google_maps_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link Mapa')),
                ('latitud', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('cliente_tiene_insumos', models.BooleanField(default=False, help_text='Si es True, NO se cobra el extra de insumos.', verbose_name='Cliente pone insumos')),
                ('precio_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notas', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_creadas', to=settings.AUTH_USER_MODEL)),
                ('enfermero', models.ForeignKey(blank=True, help_text='Puede quedar vacío inicialmente si es una Guardia por asignar.', limit_choices_to={'rol': 'ENFERMERO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_asignadas', to=settings.AUTH_USER_MODEL)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appointments.appointmentstatus')),
                ('paciente', models.ForeignKey(limit_choices_to={'rol': 'CLIENTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='citas_paciente', to=settings.AUTH_USER_MODEL)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.service')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['-fecha', '-hora_inicio'],
            },
        ),
    ]
