# Generated by Django 4.2.4 on 2025-11-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='direccion_alternativa',
        ),
        migrations.AddField(
            model_name='appointment',
            name='direccion_servicio',
            field=models.TextField(blank=True, help_text='Dirección escrita exacta donde irá el enfermero.', verbose_name='Dirección del Servicio'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='google_maps_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link Google Maps'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='referencia_servicio',
            field=models.TextField(blank=True, null=True, verbose_name='Referencia'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='cliente_tiene_insumos',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='hora_fin_servicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Fin'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='hora_inicio_servicio',
            field=models.TimeField(verbose_name='Hora Cita'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='hora_salida_base',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Salida (Buffer)'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='tipo_ubicacion',
            field=models.CharField(choices=[('DOMICILIO', 'Domicilio del Paciente'), ('OTRA', 'Otra Ubicación (Alternativa)'), ('LOCAL', 'En Local / Base')], default='DOMICILIO', max_length=20),
        ),
    ]
