# Generated by Django 4.2.4 on 2025-11-20 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_limite_sugerida', models.DateField(help_text='Fecha ideal para la siguiente dosis')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Gestión'), ('CONTACTADO', 'Cliente Contactado'), ('AGENDADO', 'Convertido en Cita'), ('CANCELADO', 'Descartado')], default='PENDIENTE', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recordatorio de Dosis',
                'verbose_name_plural': 'Recordatorios de Dosis',
                'ordering': ['fecha_limite_sugerida'],
            },
        ),
        migrations.AlterModelOptions(
            name='appointmentstatus',
            options={},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='referencia_servicio',
        ),
        migrations.AddField(
            model_name='appointment',
            name='es_reagendada',
            field=models.BooleanField(default=False, help_text='Si esta cita viene de un recordatorio/seguimiento.'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='cliente_tiene_insumos',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='direccion_servicio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='enfermero',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'ENFERMERO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='google_maps_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='hora_fin',
            field=models.TimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='hora_inicio',
            field=models.TimeField(),
        ),
        migrations.DeleteModel(
            name='NurseSchedule',
        ),
        migrations.AddField(
            model_name='appointmentreminder',
            name='cita_origen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recordatorios_generados', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='appointmentreminder',
            name='enfermero_sugerido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recordatorios_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointmentreminder',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointmentreminder',
            name='servicio_sugerido',
            field=models.ForeignKey(help_text='El servicio que toca (ej: Misma inyección)', on_delete=django.db.models.deletion.CASCADE, to='services.service'),
        ),
    ]
