# Generated by Django 4.2.4 on 2025-11-20 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointmentreminder_alter_appointmentstatus_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='referencia_servicio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
