# Generated by Django 4.2.4 on 2025-11-20 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
        ('appointments', '0003_appointment_referencia_servicio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointmentreminder',
            options={'ordering': ['fecha_limite_sugerida', '-fecha_creacion'], 'verbose_name': 'Recordatorio / Lead', 'verbose_name_plural': 'Recordatorios y Leads'},
        ),
        migrations.AddField(
            model_name='appointmentreminder',
            name='medicamento_externo',
            field=models.CharField(blank=True, help_text="Llenar solo si viene de la Web (ej: 'Neurobión', 'Vitamina C').", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='appointmentreminder',
            name='origen',
            field=models.CharField(choices=[('SISTEMA', 'Generado por Cierre de Cita'), ('WEB', 'Solicitud desde Landing Page')], default='SISTEMA', help_text='Indica si fue automático (SISTEMA) o un Lead (WEB).', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointmentreminder',
            name='cita_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recordatorios_generados', to='appointments.appointment'),
        ),
        migrations.AlterField(
            model_name='appointmentreminder',
            name='fecha_limite_sugerida',
            field=models.DateField(blank=True, help_text='Fecha ideal para la siguiente dosis. Puede estar vacía al inicio.', null=True),
        ),
        migrations.AlterField(
            model_name='appointmentreminder',
            name='paciente',
            field=models.ForeignKey(limit_choices_to={'rol': 'CLIENTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointmentreminder',
            name='servicio_sugerido',
            field=models.ForeignKey(blank=True, help_text='El servicio que toca (ej: Misma inyección). Vacío si es solicitud externa.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.service'),
        ),
    ]
