# Generated by Django 4.2.4 on 2025-11-21 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_medication'),
        ('appointments', '0004_alter_appointmentreminder_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentreminder',
            name='medicamento_catalogo',
            field=models.ForeignKey(blank=True, help_text='Si se selecciona, calcula la fecha usando Meses/Años.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.medication', verbose_name='Medicamento (Catálogo)'),
        ),
        migrations.AlterField(
            model_name='appointmentreminder',
            name='fecha_limite_sugerida',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentreminder',
            name='medicamento_externo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentreminder',
            name='origen',
            field=models.CharField(choices=[('SISTEMA', 'Generado por Cierre de Cita'), ('WEB', 'Solicitud desde Landing Page')], default='SISTEMA', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointmentreminder',
            name='servicio_sugerido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.service'),
        ),
    ]
