# Generated by Django 4.2.4 on 2025-12-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointmentreminder_medicamento_catalogo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentreminder',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Gestión'), ('CONTACTADO', 'Cliente Contactado'), ('AGENDADO', 'Convertido en Cita'), ('CANCELADO', 'Descartado'), ('EXPIRADO', 'Vencido sin Gestión'), ('FALLO_ENVIO', 'Error al Enviar Recordatorio')], default='PENDIENTE', max_length=20),
        ),
    ]
