# Generated by Django 4.2.4 on 2025-12-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_alter_appointmentreminder_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentreminder',
            name='fecha_ultima_aplicacion',
            field=models.DateField(blank=True, help_text='Fecha base para el cálculo', null=True),
        ),
    ]
