# Generated by Django 6.0 on 2026-02-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_appointmentreminder_fecha_ultima_aplicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentreminder',
            name='dosis_actual',
            field=models.PositiveIntegerField(default=1, help_text='Para medicamentos secuenciales, indica qué dosis es esta (1ra, 2da, etc).', verbose_name='No. Dosis Actual'),
        ),
    ]
