# Generated by Django 4.2.4 on 2025-11-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='google_maps_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link Google Maps'),
        ),
    ]
