"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
#SECRET_KEY = 'django-insecure-66s#9i%dd0h*6e$z9%w!m32-&7&^r&q#!efyzpjd-_=z4lf69l'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '').split(',')
CSRF_TRUSTED_ORIGINS = [
    'https://aa9defe23ded.ngrok-free.app',
    'http://127.0.0.1:8000',  # Para que te siga funcionando en local
]
#ALLOWED_HOSTS = []

AUTH_USER_MODEL = 'users.User'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # ... apps de django ...
    'widget_tweaks',
    'django_select2',

    # Mis Apps (dentro de CoreApps)
    'CoreApps.users',
    'CoreApps.services',
    'CoreApps.appointments',
    'CoreApps.notifications',
    'CoreApps.main',
    'CoreApps.scheduling',
    'CoreApps.reports',
    'CoreApps.chat',
    'CoreApps.payments',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Guayaquil'
#TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

WASENDERAPI_API_KEY = os.getenv('WASENDERAPI_API_KEY')
WASENDERAPI_BASE_URL = os.getenv('WASENDERAPI_BASE_URL')

#WAAPI_INSTANCE_ID = os.getenv('WAAPI_INSTANCE_ID')
#WAAPI_API_TOKEN = os.getenv('WAAPI_API_TOKEN')

GOOGLE_MAPS_API_KEY = os.getenv('GOOGLE_MAPS_API_KEY')
#WAAPI_INSTANCE_ID = '67602'
#WAAPI_API_TOKEN = 'QBjqX9gQ7fm2VNfklpvXP345L4W0lV9Dcr7ZQB5ffc6ef363'

# WASenderAPI Configuration
#WASENDERAPI_API_KEY = os.getenv('WASENDERAPI_API_KEY')
#WASENDERAPI_BASE_URL = os.getenv('WASENDERAPI_BASE_URL')
print(f"WASenderAPI Key loaded: {WASENDERAPI_API_KEY is not None and len(WASENDERAPI_API_KEY) > 0}")
print(f"WASenderAPI Base URL loaded: {WASENDERAPI_BASE_URL}")

# Configuración de email

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = "smtp.gmail.com"
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')      # <--- Cambio
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD') # <--- Cambio


LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'  # Ahora sí, al loguearse van al dashboard
LOGOUT_REDIRECT_URL = 'login'