# Generated by Django 6.0 on 2026-03-14 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm_marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=20, unique=True, verbose_name='Teléfono (WhatsApp)')),
                ('no_leido', models.BooleanField(default=True, verbose_name='Mensaje no leído')),
                ('fecha_ultimo_mensaje', models.DateTimeField(auto_now_add=True)),
                ('contacto_crm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversaciones', to='crm_marketing.crmcontact')),
            ],
            options={
                'verbose_name': 'Conversación de WhatsApp',
                'verbose_name_plural': 'Conversaciones de WhatsApp',
                'ordering': ['-fecha_ultimo_mensaje'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_entrante', models.BooleanField(default=True, verbose_name='¿Es mensaje entrante?')),
                ('contenido', models.TextField(verbose_name='Contenido del Mensaje')),
                ('estado_envio', models.CharField(blank=True, help_text='Ej: Sent, Delivered, Read, Failed (para salientes)', max_length=20, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='chat.whatsappconversation')),
            ],
            options={
                'verbose_name': 'Mensaje de WhatsApp',
                'verbose_name_plural': 'Mensajes de WhatsApp',
                'ordering': ['fecha'],
            },
        ),
    ]
