# Generated by Django 6.0 on 2026-03-17 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('crm_marketing', '0003_mensajecampana'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(choices=[('INBOUND', 'Entrante (Del Cliente)'), ('OUTBOUND', 'Saliente (Hacia el Cliente)')], max_length=15)),
                ('texto', models.TextField(blank=True, null=True)),
                ('wasender_message_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('estado_envio', models.CharField(choices=[('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado'), ('LEIDO', 'Leído'), ('ERROR', 'Error')], default='ENVIADO', max_length=20)),
                ('fecha_mensaje', models.DateTimeField(auto_now_add=True)),
                ('leido_por_operador', models.BooleanField(default=False)),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_chat', to='crm_marketing.crmcontact')),
            ],
            options={
                'verbose_name': 'Mensaje de Chat CRM',
                'verbose_name_plural': 'Mensajes de Chat CRM',
                'ordering': ['fecha_mensaje'],
            },
        ),
    ]
