# Generated by Django 6.0 on 2026-03-24 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmensaje',
            name='media_type',
            field=models.CharField(choices=[('TEXT', 'Texto'), ('IMAGE', 'Imagen'), ('VIDEO', 'Video'), ('AUDIO', 'Audio/Voz'), ('DOCUMENT', 'Documento')], default='TEXT', max_length=20),
        ),
        migrations.AddField(
            model_name='chatmensaje',
            name='media_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
