# Generated by Django 6.0 on 2026-03-24 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatmensaje_media_type_chatmensaje_media_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmensaje',
            name='media_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='chatmensaje',
            name='mimetype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
