# Generated by Django 4.2.4 on 2025-02-07 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nept_id', models.CharField(max_length=50, unique=True, verbose_name='ID Nept')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del producto')),
                ('administration_type', models.CharField(max_length=100, verbose_name='Tipo de administración')),
                ('sale_form', models.CharField(max_length=100, verbose_name='Forma de venta')),
                ('specialty', models.CharField(max_length=100, verbose_name='Especialidad')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
