# Generated by Django 4.2.4 on 2025-03-10 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('medication_type', models.CharField(choices=[('drug', 'Medicamento'), ('vaccine', 'Vacuna'), ('suero', 'Suero')], max_length=20)),
                ('route_of_administration', models.CharField(help_text='Ej: Oral, Intramuscular, Endovenoso, etc.', max_length=50)),
                ('form_of_sale', models.CharField(help_text='Ej: Bajo receta, OTC, etc.', max_length=50)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='store.manufacturer')),
            ],
        ),
    ]
