# Generated by Django 4.2.4 on 2025-03-10 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(max_length=50)),
                ('expiration_date', models.DateField()),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('storage_conditions', models.CharField(blank=True, help_text='Ej: mantener en frío', max_length=255, null=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='store.medication')),
            ],
        ),
    ]
