# Generated by Django 4.2.4 on 2025-03-10 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('store', '0002_medicationlot'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationlot',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medication_lots', to='common.location'),
        ),
    ]
