# Generated by Django 4.2.4 on 2025-02-08 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_suerotherapyproduct_vaccine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuerotherapyProduct',
        ),
        migrations.DeleteModel(
            name='Vaccine',
        ),
    ]
