# Generated by Django 4.2.4 on 2025-02-28 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='patient',
            name='related_users',
            field=models.ManyToManyField(help_text='Users associated with this patient.', related_name='patients_related', to=settings.AUTH_USER_MODEL, verbose_name='Related Users'),
        ),
    ]
