# Generated by Django 4.2.4 on 2025-02-07 21:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0003_alter_patient_address_alter_patient_birth_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='admins',
        ),
        migrations.AddField(
            model_name='patient',
            name='related_users',
            field=models.ManyToManyField(help_text='Users associated with this patient.', related_name='patients_related', to=settings.AUTH_USER_MODEL, verbose_name='Related Users'),
        ),
    ]
