# Generated by Django 4.2.4 on 2025-11-20 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0002_appointmentreminder_alter_appointmentstatus_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('TRANSFERENCIA', 'Transferencia Bancaria'), ('DEPOSITO', 'Depósito Bancario'), ('TARJETA', 'Tarjeta de Crédito/Débito (Link)'), ('EFECTIVO', 'Efectivo (Cobrado por Enfermero)')], default='TRANSFERENCIA', max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Verificación'), ('APROBADO', 'Aprobado / Cobrado'), ('RECHAZADO', 'Rechazado / No Acreditado')], default='PENDIENTE', max_length=20)),
                ('banco_origen', models.CharField(blank=True, help_text='Banco desde donde envía el cliente (ej: Pichincha, Guayaquil).', max_length=100, null=True, verbose_name='Banco de Origen')),
                ('banco_destino', models.CharField(blank=True, help_text='Banco de Hola Enfermera donde se recibió el dinero.', max_length=100, null=True, verbose_name='Banco de Destino')),
                ('titular_cuenta_origen', models.CharField(blank=True, help_text='Nombre del dueño de la cuenta desde donde se transfirió (a veces no es el paciente).', max_length=200, null=True, verbose_name='Nombre Titular Cta Origen')),
                ('numero_documento', models.CharField(blank=True, help_text='Código único de la transferencia o número de comprobante.', max_length=100, null=True, verbose_name='N° Documento / Ref.')),
                ('comprobante_imagen', models.ImageField(blank=True, help_text='Foto/Captura del voucher.', null=True, upload_to='pagos/comprobantes/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_verificacion', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('cita', models.ForeignKey(help_text='Cita a la que abona este pago.', on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='appointments.appointment')),
                ('registrado_por', models.ForeignKey(help_text='Usuario que subió el pago.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Gestión de Pagos',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
