# Generated by Django 4.2.4 on 2025-03-10 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('inyeccion', 'Inyección'), ('suero', 'Aplicación de suero'), ('vacunacion', 'Vacunación'), ('sueroterapia', 'Sueroterapia')], max_length=20)),
                ('appointment_date', models.DateTimeField()),
                ('location', models.CharField(help_text='Dirección o local de atención', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('completed', 'Completada'), ('canceled', 'Cancelada')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nurse', models.ForeignKey(limit_choices_to={'user_type': 'nurse'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_appointments', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'user_type': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicationAdministration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(help_text='Dosis aplicada, ej: 5ml, 1 ampolla', max_length=50)),
                ('administration_time', models.DateTimeField(auto_now_add=True)),
                ('administered_by', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'nurse'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications_administered', to='services.serviceappointment')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrations', to='store.medication')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_prescription', models.BooleanField(default=False)),
                ('doctor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('doctor_license', models.CharField(blank=True, max_length=50, null=True)),
                ('consent_given', models.BooleanField(default=False, help_text='Consentimiento informado')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_detail', to='services.serviceappointment')),
            ],
        ),
    ]
