# Generated by Django 4.2.4 on 2025-03-10 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_medicaldetail_consent_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceappointment',
            name='service_type',
            field=models.CharField(choices=[('inyeccion', 'Inyección'), ('med_especialidad', 'Aplicación de Medicamento de Especialidad'), ('suero', 'Aplicación de Suero'), ('sueroterapia', 'Sueroterapia'), ('vacunacion', 'Vacunación'), ('guardias', 'Guardias'), ('otros', 'Otros procedimientos')], max_length=20),
        ),
    ]
