# Generated by Django 4.2.4 on 2025-03-10 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_location_location_type'),
        ('services', '0003_alter_serviceappointment_service_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceappointment',
            name='location',
        ),
        migrations.AddField(
            model_name='serviceappointment',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Sucursal donde se realizará el servicio (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_branch', to='common.location'),
        ),
        migrations.AddField(
            model_name='serviceappointment',
            name='order_location',
            field=models.ForeignKey(blank=True, help_text='Dirección a domicilio para el servicio (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_domicile', to='common.orderlocation'),
        ),
        migrations.AddField(
            model_name='serviceappointment',
            name='service_place_type',
            field=models.CharField(choices=[('branch', 'Sucursal'), ('domicile', 'Domicilio')], default='branch', max_length=20),
        ),
    ]
