# Generated by Django 4.2.4 on 2025-02-28 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('store', '0004_delete_suerotherapyproduct_delete_vaccine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(verbose_name='Edad')),
                ('document_date', models.DateField(auto_now_add=True, verbose_name='Fecha del Documento')),
                ('signature', models.ImageField(upload_to='consents/', verbose_name='Firma del Consentimiento')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Consentimiento',
                'verbose_name_plural': 'Consentimientos',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Doctor')),
                ('specialty', models.CharField(blank=True, max_length=100, null=True, verbose_name='Especialidad')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Correo')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_date', models.DateField(auto_now_add=True, verbose_name='Fecha de la Receta')),
                ('pdf', models.FileField(upload_to='prescriptions/', verbose_name='PDF de la Receta')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='processes.doctor', verbose_name='Doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
            },
        ),
        migrations.CreateModel(
            name='VaccineApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('location', models.CharField(choices=[('domicile', 'A domicilio'), ('local', 'En el local')], max_length=20, verbose_name='Ubicación')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Final')),
                ('next_application', models.DateField(blank=True, null=True, verbose_name='Próxima Aplicación')),
                ('consent', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='processes.consent', verbose_name='Consentimiento')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='patients.patient', verbose_name='Paciente')),
                ('prescription', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='processes.prescription', verbose_name='Receta')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Aplicación de vacuna',
                'verbose_name_plural': 'Aplicaciones de vacunas',
            },
        ),
        migrations.CreateModel(
            name='SuerotherapyApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('location', models.CharField(choices=[('domicile', 'A domicilio'), ('local', 'En el local')], max_length=20, verbose_name='Ubicación')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Final')),
                ('next_application', models.DateField(blank=True, null=True, verbose_name='Próxima Aplicación')),
                ('consent', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='processes.consent', verbose_name='Consentimiento')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='patients.patient', verbose_name='Paciente')),
                ('prescription', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='processes.prescription', verbose_name='Receta')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Aplicación de sueroterapia',
                'verbose_name_plural': 'Aplicaciones de sueroterapia',
            },
        ),
        migrations.CreateModel(
            name='ServiceFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('vaccine', 'Aplicación de vacuna'), ('suerotherapy', 'Aplicación de sueroterapia'), ('serum', 'Aplicación de suero')], max_length=20, verbose_name='Tipo de Servicio')),
                ('location', models.CharField(choices=[('local', 'En el local'), ('domicile', 'A domicilio')], max_length=20, verbose_name='Ubicación')),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tarifa')),
            ],
            options={
                'verbose_name': 'Tarifa de Servicio',
                'verbose_name_plural': 'Tarifas de Servicio',
                'unique_together': {('service_type', 'location')},
            },
        ),
        migrations.CreateModel(
            name='SerumApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('location', models.CharField(choices=[('domicile', 'A domicilio'), ('local', 'En el local')], max_length=20, verbose_name='Ubicación')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio del Servicio')),
                ('consent', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='processes.consent', verbose_name='Consentimiento')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='patients.patient', verbose_name='Paciente')),
                ('prescription', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='processes.prescription', verbose_name='Receta')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Aplicación de suero',
                'verbose_name_plural': 'Aplicaciones de suero',
            },
        ),
    ]
