# Generated by Django 4.2.4 on 2025-12-09 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0006_alter_appointmentreminder_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_intento', models.DateTimeField(auto_now_add=True)),
                ('enviado', models.BooleanField(default=False)),
                ('respuesta_api', models.TextField(blank=True, null=True)),
                ('metodo', models.CharField(default='WHATSAPP', max_length=50)),
                ('recordatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_notificaciones', to='appointments.appointmentreminder')),
            ],
        ),
    ]
