# Generated by Django 4.2.4 on 2025-11-20 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('icono', models.ImageField(blank=True, null=True, upload_to='servicios/iconos/')),
            ],
            options={
                'verbose_name': 'Categoría de Servicio',
                'verbose_name_plural': 'Categorías de Servicios',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio del Servicio')),
                ('precio_insumos', models.DecimalField(decimal_places=2, default=5.0, help_text='Se suma si el cliente NO tiene sus propios insumos.', max_digits=10, verbose_name='Costo Adicional Insumos')),
                ('incluye_insumos_por_defecto', models.BooleanField(default=False, help_text='Si es True (ej: Sueroterapia), el precio base ya cubre todo.')),
                ('duracion_minutos', models.PositiveIntegerField(help_text='Tiempo real ejecutando el servicio con el paciente.', verbose_name='Duración Servicio (min)')),
                ('tiempo_traslado_minutos', models.PositiveIntegerField(default=30, help_text='Tiempo estimado que el enfermero necesita para llegar (Buffer Previo).', verbose_name='Tiempo Traslado Default (min)')),
                ('es_guardia', models.BooleanField(default=False, help_text='Si es True, requiere validación de día completo o turno largo (8h, 12h, 24h).', verbose_name='Es Guardia')),
                ('requiere_retorno', models.BooleanField(default=False, help_text='Para servicios tipo "Bumerán" (Puesta y retiro de suero).', verbose_name='Requiere Retorno')),
                ('tiempo_espera_retorno', models.PositiveIntegerField(blank=True, default=0, help_text='Ej: 6 horas para retirar el suero.', verbose_name='Tiempo para retiro (horas)')),
                ('permite_local', models.BooleanField(default=True, verbose_name='Disponible en Base/Local')),
                ('permite_domicilio', models.BooleanField(default=True, verbose_name='Disponible a Domicilio')),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='services.servicecategory')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
    ]
