# Generated by Django 4.2.4 on 2025-11-20 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('icono', models.ImageField(blank=True, null=True, upload_to='servicios/iconos/')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio del Servicio')),
                ('precio_insumos', models.DecimalField(decimal_places=2, default=5.0, help_text='Se suma automáticamente si el cliente NO tiene sus propios insumos.', max_digits=10, verbose_name='Costo Insumos Extra')),
                ('incluye_insumos_por_defecto', models.BooleanField(default=False, help_text='Si marcas esto (ej: Sueroterapia), el precio base ya es el final.', verbose_name='Insumos incluidos')),
                ('duracion_horas', models.PositiveIntegerField(default=1, help_text='Tiempo que se bloquea en la agenda. Estándar: 1 hora. Guardias: 8, 12, 24.', verbose_name='Duración (Horas)')),
                ('es_guardia', models.BooleanField(default=False, help_text='Si es True, requiere validación especial (bloqueo de jornada completa).', verbose_name='Es Guardia')),
                ('requiere_retorno', models.BooleanField(default=False, help_text='Si es True, el sistema deberá agendar una segunda cita para el retiro (ej: sacar el suero).', verbose_name='Requiere Retorno')),
                ('tiempo_espera_retorno', models.PositiveIntegerField(blank=True, default=0, help_text='Ej: Si el suero dura 6 horas, poner 6. El sistema sugerirá la cita de retiro 6h después.', verbose_name='Horas para retiro')),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='services.servicecategory')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
    ]
