# Generated by Django 4.2.4 on 2025-11-21 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('frecuencia_valor', models.PositiveIntegerField(default=1, help_text='Ej: 6 (para 6 meses), 1 (para 1 año).', verbose_name='Cada cuánto...')),
                ('frecuencia_unidad', models.CharField(choices=[('DIAS', 'Días'), ('MESES', 'Meses'), ('ANIOS', 'Años')], default='MESES', max_length=10, verbose_name='Unidad de Tiempo')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Medicamento (Catálogo)',
                'verbose_name_plural': 'Catálogo de Medicamentos',
            },
        ),
    ]
