# Generated by Django 6.0 on 2026-01-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_medication'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='es_recurrente',
            field=models.BooleanField(default=False, help_text='Si se marca, el sistema generará automáticamente el siguiente recordatorio al completar el actual.', verbose_name='Es Recurrente / Vitalicio'),
        ),
    ]
