# Generated by Django 6.0 on 2026-02-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_medication_es_recurrente'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='es_secuencial',
            field=models.BooleanField(default=False, help_text='Si se marca, el sistema seguirá un mapa de dosis finito (ej: 1ra, 2da, 3ra dosis).', verbose_name='Es Esquema Secuencial (Vacunas)'),
        ),
    ]
