# Generated by Django 6.0 on 2026-02-03 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_medication_es_secuencial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationDoseStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_dosis_siguiente', models.PositiveIntegerField(help_text='A qué número de dosis saltamos tras completar la actual.', verbose_name='Dosis Siguiente')),
                ('espera_valor', models.PositiveIntegerField(default=1, verbose_name='Esperar...')),
                ('espera_unidad', models.CharField(choices=[('DIAS', 'Días'), ('MESES', 'Meses'), ('ANIOS', 'Años')], default='MESES', max_length=10, verbose_name='Unidad de Tiempo')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos_esquema', to='services.medication')),
            ],
            options={
                'verbose_name': 'Paso de Esquema',
                'verbose_name_plural': 'Pasos de Esquemas de Dosis',
                'ordering': ['medicamento', 'numero_dosis_siguiente'],
                'unique_together': {('medicamento', 'numero_dosis_siguiente')},
            },
        ),
    ]
