# Generated by Django 4.2.4 on 2025-11-20 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NurseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(blank=True, choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], help_text='Para turnos fijos (ej: Todos los Lunes)', null=True)),
                ('fecha_especifica', models.DateField(blank=True, help_text='Para excepciones o días extra (ej: 2025-12-25)', null=True)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('descanso_inicio', models.TimeField(blank=True, null=True)),
                ('descanso_fin', models.TimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('enfermero', models.ForeignKey(limit_choices_to={'rol': 'ENFERMERO'}, on_delete=django.db.models.deletion.CASCADE, related_name='turnos_trabajo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Turno de Enfermero',
                'verbose_name_plural': 'Gestión de Turnos',
                'ordering': ['enfermero', 'dia_semana', 'fecha_especifica'],
            },
        ),
    ]
